[package]
name = "eeric-interpreter"
version = "0.0.5"
edition = "2021"
description = "A front-end abstraction layer over eeric"
license = "MIT"

[lib]
crate-type = ["rlib", "cdylib"]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[dependencies]
eeric = "0.0.11"
